# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Z7.xdc

# Block Designs: bd/SDW/SDW.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDW || ORIG_REF_NAME==SDW} -quiet] -quiet

# IP: bd/SDW/ip/SDW_processing_system7_0_0/SDW_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDW_processing_system7_0_0 || ORIG_REF_NAME==SDW_processing_system7_0_0} -quiet] -quiet

# IP: bd/SDW/ip/SDW_PmodMAXSONAR_0_0/SDW_PmodMAXSONAR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDW_PmodMAXSONAR_0_0 || ORIG_REF_NAME==SDW_PmodMAXSONAR_0_0} -quiet] -quiet

# IP: bd/SDW/ip/SDW_PmodOLEDrgb_0_0/SDW_PmodOLEDrgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDW_PmodOLEDrgb_0_0 || ORIG_REF_NAME==SDW_PmodOLEDrgb_0_0} -quiet] -quiet

# IP: bd/SDW/ip/SDW_axi_gpio_0_0/SDW_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDW_axi_gpio_0_0 || ORIG_REF_NAME==SDW_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SDW/ip/SDW_axi_smc_0/SDW_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDW_axi_smc_0 || ORIG_REF_NAME==SDW_axi_smc_0} -quiet] -quiet

# IP: bd/SDW/ip/SDW_rst_ps7_0_50M_0/SDW_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDW_rst_ps7_0_50M_0 || ORIG_REF_NAME==SDW_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: f:/FPGA_Project/SonarDistanceWarning/SonarDistanceWarning.gen/sources_1/bd/SDW/SDW_ooc.xdc
